<div class="tvd-row">
    <div class="tvd-col tvd-m3">
        <?php if (($setting['multiple'] && empty($key)) || !$setting['multiple']): ?>
            <?php echo $setting['label']; ?>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </div>
    <div class="tvd-col tvd-m3">
        <input type="<?php echo $setting['type']; ?>" value="<?php echo $value; ?>">
    </div>
    <div class="tvd-col tvd-m6">
        <?php if (($setting['multiple'] && empty($key)) || !$setting['multiple']): ?>
            <a class='tvd-waves-effect tvd-waves-light tvd-btn-small tvd-btn-green tvd-save-option'><?php echo __("Save", TVE_DASH_TRANSLATE_DOMAIN); ?> </a>
            <?php if ($setting['multiple']): ?>
                <a class='tvd-waves-effect tvd-waves-light tvd-btn-small tvd-btn-blue tvd-add-option'><?php echo __("Add", TVE_DASH_TRANSLATE_DOMAIN); ?> </a>
            <?php endif; ?>
        <?php else: ?>
            <a class='tvd-waves-effect tvd-waves-light tvd-btn-small tvd-btn-red tvd-delete-option'><?php echo __("Delete", TVE_DASH_TRANSLATE_DOMAIN); ?> </a>
        <?php endif; ?>
    </div>
</div>