<li class="<#= apiName #>_row tve-inside-collapsable-list-item clearfix">
    <span class="pull-left">
        <#= apiName #>
    </span>
    <span class="pull-right">
        <a class="tl-edit-api-connection tve-prevent-click tve-btn tve-btn-icon tve-btn-link-icon-red" href="javascript:void(0)" rel="<#= apiName #>">
            <span class="tve-icon-pencil"></span>
        </a>
        <a class="tl-remove-api-connection tve-prevent-click tve-btn tve-btn-icon tve-btn-link-icon-red" href="javascript:void(0)" rel="<#= apiName #>">
            <span class="tve-icon-trash-o"></span>
        </a>
    </span>
</li>